### ISSUE TITLE
165 PLan Loan amt not Match with LIC

### ISSUE THREAD

**Issue by shahtd1** [BimaMitra/BimaMitra#18]
In Plan 165, when we take loan from LIC Loyalty addition not included in calculate loan amt. it is also confirm with Patki sir. Query Raised from KK Consultancy. (Nirav Mistry - Surat)

**Comment by DeepakJalan** [comment]
@shahtd1 Please provide the Loan Status Report from the branch so that we can verify the calculation & implement accordingly.

**Comment by DeepakJalan** [comment]
Removed Loyalty From Loan Calculation. 

![image](https://user-images.githubusercontent.com/2452705/53149425-a5f24380-35d3-11e9-9d61-590fe61ae0f8.png)
